version: '3.8'

services:
  db:
    container_name: todolist-mysql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10