name: CI for TDD and API REST Tests
on:
  push:
    branches:
      - master-backend
  pull_request:
    branches:
      - master-backend
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: todolist
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        volumes:
          - ${{ github.workspace }}/init.sql:/docker-entrypoint-initdb.d/init.sql

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Run TDD Tests
        run: mvn test -Dtest="tddTest.**"
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/todolist
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD:

      - name: Run REST API Tests
        run: mvn test -Dtest="restTest.**"
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/todolist
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: