name: CI for TDD and API REST Tests

on:
  push:
    branches:
      - master-backend
  pull_request:
    branches:
      - master-backend

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      
      # Configuración de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Start MySQL with Docker Compose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
      
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
      
      - name: Run TDD Tests
        run: mvn test -Dtest="tddTest.**"
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/todolist
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ''
      
      - name: Run REST API Tests
        run: mvn test -Dtest="restTest.**"
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/todolist
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ''
